export const questions = {
  friendly: {
   truth: [
      "What's the funniest memory you have with your friends?",
      "If you could have any superpower, what would it be?",
      "What's your most embarrassing moment at school?",
      "What's your biggest pet peeve?",
      "Have you ever laughed so hard you cried?",
      "What's your favorite movie and why?",
      "If you could change your name, what would it be?",
      "What's one thing you can't live without?",
      "What's your weirdest habit?",
      "What's your most-used app on your phone?",
      "Who’s your favorite teacher and why?",
      "Have you ever accidentally sent a message to the wrong person?",
      "What’s your favorite food combo that others think is weird?",
      "What’s your dream vacation destination?",
      "Who would you call first if you won the lottery?",
      "Have you ever been caught lying?",
      "What’s your favorite childhood cartoon?",
      "Who’s your celebrity crush?",
      "Have you ever been in trouble at school?",
      "What’s your hidden talent?",
      "If you could live anywhere, where would it be?",
      "What’s your favorite song to sing in the shower?",
      "What’s your favorite memory from childhood?",
      "Have you ever had a nickname you didn’t like?",
      "What’s the weirdest food you’ve ever tried?",
      "What’s your biggest fear?",
      "If you could time travel, where would you go?",
      "What’s your favorite ice cream flavor?",
      "Who do you text the most?",
      "What’s your favorite subject in school?",
      "Have you ever pretended to be sick to skip school?",
      "What’s the most annoying trend you’ve seen?",
      "If you could trade lives with someone for a day, who would it be?",
      "Have you ever broken something and blamed someone else?",
      "What’s your favorite emoji?",
      "Who makes you laugh the most?",
      "What’s the weirdest dream you’ve ever had?",
      "What’s your favorite holiday?",
      "Have you ever lost something important?",
      "What’s your favorite fast-food restaurant?",
      "What’s your go-to comfort show or movie?",
      "What’s the longest you’ve gone without showering?",
      "If you could meet anyone in the world, who would it be?",
      "Have you ever failed a test?",
      "What’s your favorite board or video game?",
      "What’s something you’re proud of?",
      "Have you ever had a funny misunderstanding?",
      "Who’s your best friend and why?",
      "What’s one skill you wish you had?",
      "What’s your dream job?",
      "If you could have a pet of any kind, what would it be?",
      "What’s your favorite snack?",
      "Who’s the last person you texted?",
      "Have you ever accidentally hurt someone?",
      "What’s your favorite outfit you own?",
      "What’s the silliest thing you’ve done in public?",
      "If you could have any talent instantly, what would it be?",
      "What’s your least favorite chore?",
      "Have you ever laughed at the wrong moment?",
      "What’s something you always forget to do?",
      "What’s your weirdest fear?",
      "Have you ever tried to cook and failed?",
      "What’s the best gift you’ve ever received?",
      "What’s your favorite color and why?",
      "Have you ever fallen asleep in class?",
      "Who do you think is the funniest person you know?",
      "What’s your favorite memory this year?",
      "If you had to eat one food forever, what would it be?",
      "What’s one thing you can’t stand?",
      "Who would play you in a movie about your life?",
      "What’s your favorite outdoor activity?",
      "Have you ever cried during a movie?",
      "What’s your favorite thing to do on weekends?",
      "What’s your favorite quote or saying?",
      "Have you ever had an embarrassing typo?",
      "What’s your favorite dessert?",
      "What’s your favorite holiday tradition?",
      "Have you ever stayed up all night?",
      "What’s your favorite way to relax?",
      "If you could master any hobby instantly, what would it be?",
      "What’s something that always makes you smile?",
      "Who’s the kindest person you know?",
      "Have you ever lost a bet?",
      "What’s your favorite pizza topping?",
      "Have you ever done something silly for attention?",
      "What’s your favorite animal?",
      "What’s a song that always cheers you up?",
      "Have you ever had a funny teacher?",
      "What’s your dream car?",
      "Have you ever been on stage?",
      "What’s your favorite app or game right now?",
      "If you could visit any planet, which one would it be?",
      "What’s your most-used phrase?",
      "Have you ever kept a funny secret?",
      "What’s your favorite way to spend a rainy day?",
      "Who’s your favorite fictional character?",
      "What’s something you’re currently obsessed with?",
      "If you had a superpower for one day, what would you do?",
      "What’s the funniest video you’ve seen recently?",
      "Have you ever embarrassed yourself in front of your crush?",
      "What’s your favorite smell?",
      "If you could meet your future self, what would you ask?",
      "What’s one thing you wish you could do better?"
    ],
    dare: [
      "Do your best dance move for 10 seconds.",
      "Try to lick your elbow.",
      "Speak in a British accent for 3 rounds.",
      "Do your best animal impression.",
      "Sing the chorus of your favorite song.",
      "Show your last selfie to everyone.",
      "Do 15 jumping jacks.",
      "Balance something on your head for 30 seconds.",
      "Make a silly face and hold it for 20 seconds.",
      "Try to talk without closing your mouth for 1 minute.",
      "Do your best robot dance.",
      "Imitate a teacher everyone knows.",
      "Act like a cat until your next turn.",
      "Tell a funny joke (must make someone laugh).",
      "Do your best superhero pose.",
      "Dance with no music for 15 seconds.",
      "Pretend to be a celebrity for 1 minute.",
      "Do your best impression of your best friend.",
      "Eat something weird from the kitchen (safe to eat).",
      "Sing everything you say for the next 2 minutes.",
      "Draw a self-portrait blindfolded.",
      "Make a silly TikTok dance move.",
      "Do your best evil laugh.",
      "Do an impression of someone famous.",
      "Say the alphabet backward.",
      "Pretend to be an old person.",
      "Talk in a whisper for 2 rounds.",
      "Act like your favorite movie character.",
      "Tell a dad joke.",
      "Try to juggle 3 small items.",
      "Do your best runway walk.",
      "Say a tongue twister 3 times fast.",
      "Make up a 10-second song about yourself.",
      "Do your best fake cry.",
      "Spin around 10 times, then try to walk straight.",
      "Pretend to be a waiter taking everyone’s order.",
      "Try to keep a straight face while someone makes you laugh.",
      "Say something funny using only emojis.",
      "Pretend you’re on a cooking show.",
      "Do your best monster roar.",
      "Speak like a robot until your next turn.",
      "Do 10 squats while making funny noises.",
      "Act out your favorite meme.",
      "Try to make someone laugh in 15 seconds.",
      "Do your best magician impression.",
      "Try to make up a rap about something random.",
      "Say everything in a high-pitched voice for 2 rounds.",
      "Make a heart shape using your hands and face.",
      "Hop on one foot for 30 seconds.",
      "Pretend you’re swimming in slow motion.",
      "Sing your favorite childhood song.",
      "Draw something with your eyes closed.",
      "Balance a spoon on your nose for 10 seconds.",
      "Do your best zombie walk.",
      "Say 5 nice things about yourself.",
      "Do your best dramatic movie scene.",
      "Speak in rhyme until your next turn.",
      "Pretend you’re in a shampoo commercial.",
      "Act like you just won an award.",
      "Do your best impression of a baby.",
      "Pretend to be a news reporter for 1 minute.",
      "Try to do a cartwheel (if possible).",
      "Pretend you’re invisible for 20 seconds.",
      "Do your best fake laugh.",
      "Say the next 3 things in slow motion.",
      "Make a weird sound and keep a straight face.",
      "Do 5 push-ups while smiling.",
      "Pretend to talk to an imaginary friend.",
      "Act like a YouTuber doing an unboxing.",
      "Speak in a made-up language for 1 minute.",
      "Dance like nobody’s watching for 15 seconds.",
      "Pretend to be your favorite cartoon character.",
      "Make an animal noise every time you talk for 2 rounds.",
      "Pretend you’re stuck in slow motion.",
      "Try to pat your head and rub your stomach at the same time.",
      "Make up a funny poem on the spot.",
      "Act like you’re in a dramatic movie scene.",
      "Pretend you’re in a cooking competition.",
      "Do your best impression of a celebrity interview.",
      "Talk like a pirate until your next turn.",
      "Pretend you’re walking on the moon.",
      "Say a random fact in a dramatic voice.",
      "Do a chicken dance for 10 seconds.",
      "Try to whistle with your mouth full of water (safely).",
      "Act like you’re trapped in a box.",
      "Try to wink repeatedly for 10 seconds.",
      "Pretend to faint dramatically.",
      "Say something random in your most serious voice.",
      "Do 5 funny poses.",
      "Pretend to sneeze 5 times in a row.",
      "Talk like a villain plotting something.",
      "Say something kind to everyone playing.",
      "Pretend you’re in a scary movie.",
      "Do your best slow clap.",
      "Speak like a sports commentator.",
      "Pretend you’re holding a baby animal.",
      "Give everyone a random compliment.",
      "Do your best superhero landing.",
      "Try to balance on one foot for 20 seconds."
    ],
  },
  crush: {
   truth: [
      "What was your first impression of your crush?",
      "Who was your first crush ever?",
      "What’s your idea of a perfect date?",
      "What do you notice first about someone you like?",
      "Have you ever had a crush on a friend?",
      "What’s your love language?",
      "Who’s your celebrity crush?",
      "What kind of personality attracts you the most?",
      "Have you ever had a crush on someone you met online?",
      "What’s your biggest turn-off?",
      "Who was your first kiss?",
      "What song reminds you of your crush?",
      "What’s your favorite romantic movie?",
      "Have you ever liked two people at once?",
      "What’s the most romantic thing someone could do for you?",
      "What’s your biggest relationship fear?",
      "Have you ever had a crush on a teacher?",
      "What’s your dream date?",
      "What’s your definition of love?",
      "Have you ever been rejected?",
      "Who’s the best texter you know?",
      "Have you ever had a secret admirer?",
      "Do you believe in love at first sight?",
      "What’s your go-to flirting move?",
      "What’s something that makes you instantly smile?",
      "Who’s your current crush?",
      "If your crush asked you out, what would you do?",
      "What color reminds you of your crush?",
      "What’s your favorite compliment to receive?",
      "Have you ever had a dream about your crush?",
      "Would you rather be called cute or hot?",
      "Have you ever liked someone younger or older than you?",
      "Do you believe in soulmates?",
      "Who do you text the most right now?",
      "What’s your ideal relationship vibe — silly or serious?",
      "Have you ever been jealous of someone?",
      "What’s something you find super attractive in a person?",
      "What’s your favorite romantic song?",
      "What’s your biggest relationship red flag?",
      "Have you ever had a crush on a friend’s sibling?",
      "What would your dream couple nickname be?",
      "What’s the cutest thing someone’s done for you?",
      "Would you ever make the first move?",
      "Who gives the best hugs?",
      "What kind of dates do you find most fun?",
      "What’s one thing that always makes you blush?",
      "Would you rather get a love letter or a love text?",
      "Have you ever told your crush you liked them?",
      "What’s your favorite pet name to be called?",
      "What’s your ideal way to spend Valentine’s Day?",
      "Have you ever written a love note or message?",
      "Who was your first ever Valentine?",
      "What’s the most romantic place you can think of?",
      "Have you ever slow danced with someone you liked?",
      "Do you think you’re a good flirt?",
      "What’s one compliment you secretly love hearing?",
      "What’s the longest crush you’ve ever had?",
      "Have you ever blushed in front of your crush?",
      "What’s something your crush doesn’t know about you?",
      "Have you ever liked someone you weren’t supposed to?",
      "What’s your favorite thing to do when you like someone?",
      "Do you think your crush likes you back?",
      "Have you ever sent a risky text?",
      "Who’s the best couple you know?",
      "Would you rather fall for someone shy or outgoing?",
      "Have you ever been friend-zoned?",
      "Who would you take to prom if you could pick anyone?",
      "What’s your favorite thing about relationships?",
      "What’s your favorite romantic emoji combo?",
      "Have you ever tried to make your crush jealous?",
      "Do you prefer hugs or hand-holding?",
      "Would you rather date someone funny or smart?",
      "Have you ever given someone a flirty nickname?",
      "What’s something that gives you butterflies?",
      "Who’s the best listener you know?",
      "What’s your favorite couple from a movie or show?",
      "Would you ever confess to your crush in person?",
      "Have you ever pretended not to like someone you did?",
      "What’s your dream proposal idea?",
      "What kind of person do you usually fall for?",
      "Have you ever gotten caught staring at your crush?",
      "Would you ever write a love song or poem?",
      "Do you like public displays of affection?",
      "Have you ever kept a crush secret from your friends?",
      "Would you rather go on a picnic or watch a movie together?",
      "What’s the most awkward crush moment you’ve had?",
      "Do you believe you can fall in love as a teen?",
      "Have you ever gotten butterflies just seeing someone?",
      "What’s something your crush does that melts you?",
      "Would you rather be loved or admired?",
      "Do you get shy around people you like?",
      "What’s your favorite romantic gesture?",
      "What makes you feel most special?",
      "Would you rather your crush compliment your looks or personality?",
      "Have you ever tried to impress your crush?",
      "What’s your favorite thing to call your crush?",
      "If you could spend one day with your crush, what would you do?",
      "Do you believe love changes people?",
      "Have you ever doodled your crush’s name?",
      "What’s the cutest text you’ve ever received?",
      "Do you believe your first love never fades?",
      "What’s your favorite time to talk to your crush — morning or night?"
    ],
    dare: [
      "Text your crush a random emoji.",
      "Say three nice things about the person to your right.",
      "Send a heart emoji to someone random.",
      "Give someone in the room a compliment.",
      "Act like you’re proposing to someone for 10 seconds.",
      "Send your crush a funny meme.",
      "Write your crush’s initials on your hand (washable ink!).",
      "Give your best wink.",
      "Say something sweet about the person sitting across from you.",
      "Pretend to write a love song about your crush.",
      "Compliment everyone in the room once.",
      "Share your favorite romantic song.",
      "Give your best pickup line.",
      "Blow a kiss to someone in the group.",
      "Describe your crush using only emojis.",
      "Pretend you’re confessing your love to your crush.",
      "Say your favorite romantic movie quote.",
      "Send a flirty message to a friend (keep it friendly).",
      "Give the person to your left a cute nickname.",
      "Look someone in the eyes for 10 seconds without laughing.",
      "Pretend to ask someone out on a date.",
      "Make a heart out of your hands and hold it for 10 seconds.",
      "Say something nice about everyone in the group.",
      "Act like you’re in a romantic movie scene.",
      "Text a random heart to your best friend.",
      "Compliment someone’s smile.",
      "Say the first nice thing that comes to mind about your crush.",
      "Do your best “in love” face.",
      "Make a romantic poem on the spot.",
      "Say who in the room you’d go on a date with (as a joke).",
      "Sing a short romantic song.",
      "Act like your favorite romantic movie character.",
      "Tell everyone your dream date idea.",
      "Pretend to be on a date for 20 seconds.",
      "Give someone a virtual flower (say it out loud).",
      "Tell someone a cute secret.",
      "Describe your ideal partner in 5 words.",
      "Do your best flirty smile.",
      "Send a nice message to your best friend.",
      "Say something sweet using a song lyric.",
      "Pretend to get nervous talking to your crush.",
      "Say something you’d tell your crush if you had no fear.",
      "Pretend to slow dance with someone for 10 seconds.",
      "Give someone a compliment about their personality.",
      "Share your favorite romantic quote.",
      "Make up a silly couple nickname for two people playing.",
      "Say your favorite thing about being in love.",
      "Tell someone what you find most attractive about their personality.",
      "Pretend you’re getting a text from your crush.",
      "Give your best heart eyes look.",
      "Make a heart shape using your body somehow.",
      "Compliment the person to your right’s outfit.",
      "Say a cheesy pickup line without laughing.",
      "Pretend you’re writing a love note.",
      "Give someone an imaginary rose.",
      "Whisper something sweet (PG!) to the person next to you.",
      "Say who you think would make a great couple in this group.",
      "Make everyone smile in 10 seconds.",
      "Say the nicest thing you can think of about the person next to you.",
      "Give your best shy crush impression.",
      "Pretend to be a couple influencer for 10 seconds.",
      "Tell someone one thing that makes them awesome.",
      "Act out how you’d ask someone out.",
      "Share your dream couple activity.",
      "Say what your perfect relationship would be like.",
      "Pretend you’re nervous meeting your crush.",
      "Give a random player a fake love letter.",
      "Describe your crush’s vibe using three words.",
      "Compliment someone’s laugh.",
      "Share your favorite romantic emoji combo.",
      "Do your best blushing face.",
      "Send your best friend a text saying “you’re the best”.",
      "Pretend to serenade someone.",
      "Say a compliment starting with each letter of their name.",
      "Say something nice about the person wearing the brightest outfit.",
      "Pretend you’re getting ready for a date.",
      "Compliment someone’s hairstyle.",
      "Pretend you’re reading a love note out loud.",
      "Say what color reminds you of love.",
      "Say something kind about the person who went before you.",
      "Do your best romantic movie confession scene.",
      "Act like you’re daydreaming about your crush.",
      "Give your best “you’re cute” smile.",
      "Say the sweetest thing you can think of in 10 seconds.",
      "Send a text to a friend saying you appreciate them.",
      "Pretend to bump into your crush and say hi.",
      "Give a small compliment to everyone playing.",
      "Do your best “love struck” expression.",
      "Make a heart with your fingers and blow a kiss.",
      "Say who has the best smile here.",
      "Pretend you’re getting surprised by your crush.",
      "Say a romantic line from a song or movie.",
      "Pretend to get flustered talking to your crush.",
      "Give someone a sweet nickname right now.",
      "Tell everyone one thing that makes you happy.",
      "Say what kind of compliment you’d love to get.",
      "Pretend you’re texting your crush something sweet.",
      "Say something nice about your future partner.",
      "Give a dramatic love confession (keep it PG!).",
      "Do your best romantic laugh.",
      "Tell someone they’d make a great main character in a rom-com.",
      "Say your dream relationship goal.",
      "End the dare with a friendly air heart ❤️."
    ],
  },
  adult: {
    truth: [
      "What’s the most romantic thing you’ve ever done for someone?",
      "Who gives you butterflies every time you see them?",
      "Have you ever held hands with someone you liked?",
      "What’s your dream relationship like?",
      "What’s your favorite memory with someone special?",
      "Have you ever had a crush that turned into more?",
      "What’s your biggest relationship goal?",
      "Have you ever been surprised by someone you liked?",
      "What’s your idea of a perfect couple?",
      "What’s one thing that makes someone instantly attractive to you?",
      "What’s your favorite romantic gesture?",
      "Have you ever been on a romantic walk or date?",
      "What’s your favorite thing to do with someone you like?",
      "Have you ever planned a surprise for a crush or partner?",
      "What song always reminds you of someone you like?",
      "Would you rather cuddle or hold hands?",
      "What’s something small that makes you feel loved?",
      "Have you ever slow danced with someone?",
      "What’s your favorite romantic movie moment?",
      "Who would you call first if you had great news?",
      "What’s something romantic you’ve always wanted to try?",
      "What makes a relationship strong, in your opinion?",
      "Have you ever been someone’s secret crush?",
      "What’s your favorite way to show affection?",
      "Have you ever gotten a love note or text?",
      "What’s the sweetest message you’ve ever received?",
      "Who’s your biggest inspiration for love?",
      "Would you rather be the funny one or the romantic one?",
      "What’s your favorite couple goal activity?",
      "Have you ever written a poem or letter for someone?",
      "What’s the cutest thing someone has said to you?",
      "Would you rather go on a picnic or a movie date?",
      "Who would you want to spend a rainy day with?",
      "Have you ever shared an umbrella with someone?",
      "What’s your biggest relationship green flag?",
      "What’s the nicest compliment you’ve ever gotten?",
      "Would you rather text or call someone you like?",
      "What’s your dream anniversary date idea?",
      "What’s something you find irresistibly sweet?",
      "Have you ever felt nervous around your crush?",
      "What makes someone unforgettable to you?",
      "Would you rather watch the sunset or stargaze together?",
      "What’s your favorite thing about being loved?",
      "What’s a memory that always makes you smile?",
      "Have you ever planned a cute surprise?",
      "What makes you feel appreciated?",
      "What’s your love language?",
      "Would you rather receive flowers or a handwritten note?",
      "Who was your first real crush?",
      "What’s one quality you’d want in your future partner?",
      "Have you ever made someone blush?",
      "What’s your idea of a romantic gesture that’s simple but meaningful?",
      "Do you believe love can last forever?",
      "What’s your favorite way to spend time with someone special?",
      "Who do you feel most comfortable being yourself around?",
      "Would you rather be adored or admired?",
      "Have you ever had a song that perfectly fit your relationship?",
      "What’s your favorite romantic holiday memory?",
      "Would you rather receive a surprise or plan one?",
      "What’s your go-to outfit when you want to impress someone?",
      "What’s something someone could do that would make your day instantly better?",
      "Have you ever told someone how much they mean to you?",
      "What’s your favorite romantic movie or series?",
      "Would you rather have matching bracelets or hoodies with someone?",
      "What’s the nicest thing you’ve ever done for someone you liked?",
      "Do you believe in fate or coincidence when it comes to love?",
      "Who do you think gives the best hugs?",
      "What makes you feel instantly comfortable with someone?",
      "Would you rather get a surprise text or a surprise visit?",
      "What’s one song lyric that hits you in the feels?",
      "Have you ever been serenaded or imagined it?",
      "What’s something that makes your heart race?",
      "Would you rather write a love letter or make a romantic playlist?",
      "What’s the most memorable compliment you’ve ever received?",
      "Have you ever done something brave for love?",
      "What’s a relationship dealbreaker for you?",
      "Would you rather spend a date indoors or outdoors?",
      "What’s your favorite thing to hear from someone you like?",
      "What makes you fall for someone faster — humor or kindness?",
      "Have you ever had a special nickname from someone?",
      "What’s your favorite memory with your crush?",
      "Do you believe you can be best friends with your partner?",
      "What’s your favorite way to cheer someone up?",
      "Would you rather be loved loudly or quietly?",
      "Have you ever been surprised with a gift from someone?",
      "What’s one thing that makes you instantly happy?",
      "Would you rather go for a long walk or stay up talking all night?",
      "What’s the most thoughtful gift you’ve ever received?",
      "What’s your dream “first date” activity?",
      "Who makes you feel safe and happy?",
      "Would you rather have breakfast dates or night drives?",
      "What’s a cute couple tradition you’d love to start?",
      "What kind of couple aesthetic do you like — cozy, classy, or playful?",
      "What’s your favorite compliment to give?",
      "Would you rather dance in the rain or watch fireworks together?",
      "What’s your favorite season for romance?",
      "What makes a moment feel magical to you?",
      "Would you rather fall in love slowly or all at once?",
      "What’s something you’ve learned from a past crush or relationship?",
      "Who makes your day brighter just by being around?",
      "What’s one romantic thing you’d love to do someday?"
    ],
    dare: [
      "Send a cute good-morning text to a friend.",
      "Say one thing you find adorable about someone here.",
      "Give someone your best flirty smile.",
      "Describe your perfect date in 10 seconds.",
      "Share your favorite love song.",
      "Pretend you’re confessing your feelings in a movie scene.",
      "Write a one-line love note and read it out loud.",
      "Give a compliment using a song lyric.",
      "Say what kind of romantic gesture would make you blush.",
      "Make a heart with your hands and give it to someone.",
      "Compliment the person wearing the nicest outfit.",
      "Pretend to get a text from your crush and react dramatically.",
      "Say something you’d tell your future partner.",
      "Do your best impression of a romantic movie scene.",
      "Say one reason you’d make a great partner.",
      "Give your best wink.",
      "Say something sweet without using the word ‘love’.",
      "Share a cute memory that still makes you smile.",
      "Say your favorite pet name someone could call you.",
      "Do a 10-second slow dance with an imaginary partner.",
      "Say your favorite thing about hugs.",
      "Give your best ‘heart-eyes’ expression.",
      "Pretend you’re on a first date and introduce yourself charmingly.",
      "Say your dream couple activity.",
      "Compliment someone’s vibe or personality.",
      "Give a friend a made-up romantic nickname.",
      "Pretend to serenade someone with your favorite song.",
      "Say a cheesy romantic line without laughing.",
      "Give your best ‘I’m falling for you’ look.",
      "Describe what a perfect day with your crush would be like.",
      "Send a sweet text to your best friend or sibling.",
      "Say a romantic quote or lyric you love.",
      "Pretend you’re receiving flowers from someone special.",
      "Tell the group what your dream proposal location would be.",
      "Give someone an imaginary rose and compliment them.",
      "Pretend to take a selfie with your crush.",
      "Say what kind of date would make you happiest.",
      "Describe your dream relationship aesthetic.",
      "Say a positive affirmation about yourself as a partner.",
      "Do your best ‘I miss you’ face.",
      "Say something kind about the person to your left.",
      "Pretend you’re writing a text to someone you miss.",
      "Give your most charming smile for 5 seconds.",
      "Say your favorite romantic emoji combo.",
      "Pretend you’re in a rom-com and deliver a funny line.",
      "Say what you’d name your couple playlist.",
      "Give your best compliment to the person across from you.",
      "Act like you’re giving your crush a pep talk.",
      "Describe what a cozy night with someone would look like.",
      "Say a kind word for every person here.",
      "Pretend you’re calling someone to say goodnight.",
      "Say what you love most about romance movies.",
      "Give your best romantic movie pose.",
      "Say your favorite kind of date night food.",
      "Pretend to text something sweet and read it aloud.",
      "Give someone a nice compliment about their eyes.",
      "Say your dream couple nickname.",
      "Pretend you’re telling your crush you like them (keep it cute).",
      "Compliment someone’s laugh or smile.",
      "Describe your favorite season for dating.",
      "Say your favorite thing about falling in love.",
      "Give someone your best imaginary bouquet.",
      "Say what makes someone a good partner.",
      "Pretend to give advice to your crush.",
      "Say something that would make someone smile instantly.",
      "Pretend to get surprised with a romantic gesture.",
      "Give someone a friendly compliment using their name.",
      "Say your dream movie date pick.",
      "Do your best ‘cute and shy’ impression.",
      "Say one sweet text you’d love to receive.",
      "Pretend you’re walking hand in hand with your crush.",
      "Say what your dream Valentine’s Day would look like.",
      "Make a heart shape and hold it for 5 seconds.",
      "Say who would play your partner in a romantic movie about your life.",
      "Describe your favorite couple aesthetic (like cozy, sporty, artsy).",
      "Say one quality that makes someone instantly likeable.",
      "Pretend you’re on a call saying ‘goodnight’ sweetly.",
      "Say a random act of kindness you’d do for someone you like.",
      "Pretend to gift someone a romantic playlist.",
      "Say your favorite time of day to text someone special.",
      "Describe your dream matching-outfit idea.",
      "Say one word that describes your love style.",
      "Give your best bashful smile.",
      "Say what your first date outfit would be.",
      "Pretend to give someone a heart sticker.",
      "Say the name of a romantic song you’d dance to.",
      "Pretend to get flustered when your crush says hi.",
      "Say what small gestures make you happiest.",
      "Give your best 3-second romantic monologue.",
      "Say what kind of couple tradition you’d start.",
      "Pretend you’re writing the last line of a love story.",
      "Say something that gives you butterflies.",
      "Do your best shy laugh.",
      "Say one small thing that makes you feel cared for.",
      "Pretend to get a sweet text and smile big.",
      "Say what your dream matching gift would be.",
      "Give someone a compliment that sounds romantic but is still PG.",
      "Pretend you’re making a toast to love and friendship.",
      "End with a heart pose and say, ‘Love is awesome!’"
    ],
  },
};

export const getRandomQuestion = (mode: "friendly" | "crush" | "adult", type: "truth" | "dare"): string => {
  const modeQuestions = questions[mode][type];
  return modeQuestions[Math.floor(Math.random() * modeQuestions.length)];
};
